### ISSUE TITLE
Table not always rendered

### ISSUE THREAD

**Issue by XiaomoWu** [trey-wallis/obsidian-dashboards#594]
### Describe the bug

I apologize first that I can't find a way to 100% reproduce the issue every time. It just occurs sporadically.

The issue is that sometime when I open a note, the note is not rendered by default, even if I typed `![[title.table]]` and move the cursor to exactly the table line:

<img width="500" alt="CleanShot 2023-07-03 at 15 35 24@2x" src="https://github.com/trey-wallis/obsidian-dashboards/assets/26643668/c0027e92-9977-414d-972b-ee859dd6ec86">

The issue sometime got fixed by reload obsidian (cmd+R), but it's not guaranteed. 

### Steps to reproduce

I apologize first that I can't find a way to 100% reproduce the issue every time. It just occurs sporadically.

### Expected behavior

The table got rendered.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.5
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 22.5.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: AnuPpuccin v1.4.2
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 10
		1: Code Editor Shortcuts v1.14.0
		2: Latex Suite v1.7.3
		3: Quiet Outline v0.3.15
		4: Hider v1.2.5
		5: Style Settings v1.0.6
		6: Number Headings v1.13.0
		7: Advanced Tables v0.18.1
		8: Icon Folder v2.1.2
		9: Dashboards v6.19.1
		10: Webpage HTML Export v1.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@XiaomoWu Is this still happening in 7.0.1?

**Comment by XiaomoWu** [comment]
@trey-wallis Thank you for the update, the issue doesn't appear again.
