### ISSUE TITLE
Failed to install obsidian-dashboards

### ISSUE THREAD

**Issue by shiomiyan** [trey-wallis/obsidian-dashboards#598]
### Describe the bug

Plugin fails to install.

### Steps to reproduce

Try to install obsidian-dashboards on Obsidian community plugin browser.

My reproduced environment is as follows.

- OS: Windows10
- Obsidian: v1.3.5

### Expected behavior

It seems that the manifest URL is incorrect, and the version information in manifest.json does not match the latest version.
https://github.com/trey-wallis/obsidian-dashboards/blob/master/manifest.json#L10

Here's are screenshots of the error and the breakpoint on my Obsidian below.
![image](https://github.com/trey-wallis/obsidian-dashboards/assets/35842766/52e71e52-9013-4ea2-a9fe-236c3afd2bfa)
![image](https://github.com/trey-wallis/obsidian-dashboards/assets/35842766/531a3669-0656-4ac0-89fe-b62b0144dcbe)

I am not familiar with Obsidian's plugin development, so I apologize if I am wrong.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Obsidian Memos v1.9.7
		2: Icon Folder v2.1.2
		3: File Explorer Note Count v1.2.1
		4: Share as Gist v1.2.1
		5: Vimrc Support v0.9.0
		6: Advanced Tables v0.18.1
		7: ReadItLater v0.3.1
		8: Translate v1.4.4

### Relevant log output

```shell
Please refer to "Expected behavior".
```

**Comment by shiomiyan** [comment]
I may have been too hasty. Just haven't made the tag yet?

**Comment by MSBack** [comment]
I have the same issue. I tried to update, and got the same failure message. Then, I tried to uninstall and reinstall, which doesn't work either, so now I can't install at all (unless doing a downgraded manual install). Note: I am working on an iPad at the moment.

**Comment by Camillever** [comment]
I have also the same issue. My Obsidian is up to date also.
Just have the message "failed to install"...

**Comment by natcl** [comment]
Same error on Mac here

**Comment by qf3l3k** [comment]
I can confirm same error on Windows and macOS machine with Obsidian v1.3.5.
First was not update to update ("Failed to install") and after removing unable to install again.

**Comment by phampyk** [comment]
Having the same issue, tried to update and gave error, uninstall and tried to install and error too. Waiting for the solution :)

**Comment by trey-wallis** [comment]
Fixed in 7.0.0

**Comment by shiomiyan** [comment]
thank you for quick response!
