### ISSUE TITLE
Table embeds not rendered after 7.0 update

### ISSUE THREAD

**Issue by Wren-NLN** [trey-wallis/obsidian-dashboards#603]
### Describe the bug

Tables embedded using `![[]]` syntax no longer render in markdown editing view, only displaying button to .dashboard file. Tables render when viewing .dashboard file.

Tables render as expected after overwriting extension files with release 6.19.1.

### Steps to reproduce

Update from version 6.19.1 to version 7.0 through obsidian plugin manager.

### Expected behavior

Table renders

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Home 10.0.19045
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Royal Velvet v0.11.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 12
	Plugins enabled: 12
		1: Pluck v1.0.1
		2: Hotkey Helper v0.3.18
		3: Outliner v4.7.1
		4: Tag Wrangler v0.5.11
		5: Style Settings v1.0.6
		6: Pandoc Plugin v0.4.1
		7: Kanban v1.5.3
		8: Advanced Tables v0.18.1
		9: Folder Index v1.0.20
		10: Advanced Cursors v0.5.1
		11: Smarter Markdown Hotkeys v1.16.4
		12: Dashboards v7.0.0

**Comment by trey-wallis** [comment]
Thanks for posting this. Will look into this today.

**Comment by NaturallyAsh** [comment]
Same issue for me. Macbook Pro M1 Pro.

**Comment by trey-wallis** [comment]
Fixed in 7.0.1
